version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: stockdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/stockdb
      - FLASK_ENV=development
    volumes:
      - ./backend:/app

  dashboard:
    build: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    volumes:
      - ./dashboard:/app

volumes:
  postgres_data:
